### ISSUE TITLE
CSS Compressor not working for me

### ISSUE THREAD

**Issue by sbgraphicdesign** [backdrop-contrib/mimemail#26]
The module appears to have no effect on my Webform emails, CSS is inserted in a <style> tag in the head and CSS classes remain on all tags.
Am running PHP7.3, the PHP DOM extension is enabled and I'm also running Mailsystem module. Mimemail is configured as the default delivery and formatting options. I see no other settings I can change.
Any ideas?

**Comment by herbdool** [comment]
@sbgraphicdesign  if you create a PR, the @backdrop-contrib/bug-squad can merge it (after testing). The maintainer does not seem to be available at the moment.

**Comment by argiepiano** [comment]
The issue is that the code used in the Backdrop version is old. It was updated in D7. I'm providing a PR that cross-ports a few updates done in D7:
- https://www.drupal.org/project/mimemail/issues/2743229
- https://www.drupal.org/project/mimemail/issues/3053313

PR #40

**Comment by herbdool** [comment]
@sbgraphicdesign are you interested in testing the PR posted above?

**Comment by argiepiano** [comment]
I've done testing myself, but it'd be good to have someone else's tests

**Comment by djzwerg** [comment]
I've done a test too and it works for me. Thanks @argiepiano !

**Comment by argiepiano** [comment]
Thanks, @djzwerg! Merging.

**Comment by argiepiano** [comment]
Actually, @djzwerg - I've made a couple of tweaks. Would you mind re-testing before I merge?
