### ISSUE TITLE
Wrong namespace in upgrade path

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/mimemail#27]
Hi @Graham-72,

just saw this by accident:

https://github.com/backdrop-contrib/mimemail/blob/1.x-1.x/mimemail.install#L26

The mimemail module does two things, which aren't correct:

1. It implements migrate_update_1000() instead of mimemail_update_1000()
2. It writes to config('migrate.settings') instead of config('mimemail.settings')

So in the end this upgrade path won't work at all.

**Comment by rbargerhuff** [comment]
I can comfirm this BUG. Not only does the upgrade path won't work at all, it prevents critical db updates from running during a Drupal 7 to Backdrop CMS conversion. Here was the simple fix:

```
function mimemail_update_1000() {
  $config = config('mimemail.settings');
  ```
  
  Cheers!

**Comment by herbdool** [comment]
Thanks @rbargerhuff . Fixed on behalf of Bug Squad.
