### ISSUE TITLE
Fix Mimemail metadata callbacks for Rules

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/mimemail#29]
Mimemail currently uses inexistent Rules/Entity Plus callbacks in `mimemail.rules.inc`.

- `entity_metadata_user_roles` should be fixed to `entity_plus_metadata_user_roles`
- `entity_metadata_language_list` should be fixed to `entity_plus_metadata_language_list`

Rules depends on Entity Plus, and it uses those callbacks provided by E+ to obtain lists of user roles and languages.

**Comment by herbdool** [comment]
@argiepiano  if you create a PR, the @backdrop-contrib/bug-squad can merge it (after testing). The maintainer does not seem to be available at the moment.

**Comment by argiepiano** [comment]
Done. PR #33

**Comment by herbdool** [comment]
Thanks @argiepiano. Merging as bug squad.
