### ISSUE TITLE
Rule "Send HTML mail to all users of a role" is buggy

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/mimemail#30]
Rule "Send HTML mail to all users of a role" currently produces errors.

One of the problems is explained in #29. The other problem is that, the selection of Roles in the rule action `mimemail_to_users_of_role` provided by this module still uses numerical role IDs ("alla" D7). 

In Backdrop all role IDs are tokens (aka 'machine names'). Therefore line 116 of `mimemail.rules.inc` should be fixed to:

```php
          'type' => 'list<token>',
```

**Comment by argiepiano** [comment]
Additionally, the constant `BACKDROP_AUTHENTICATED_RID` should be changed to `BACKDROP_AUTHENTICATED_ROLE`

**Comment by herbdool** [comment]
@alanmels if you create a PR, the @backdrop-contrib/bug-squad can merge it (after testing). The maintainer does not seem to be available at the moment.

**Comment by argiepiano** [comment]
@herbdool I think you meant to ping me? PR submitted. #34

**Comment by argiepiano** [comment]
BTW, this only works if you merge #33 too.

**Comment by herbdool** [comment]
Thanks @argiepiano! Feel like making more PRs for other bugs here?
