### ISSUE TITLE
'Plaintext email only' option never saves

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/mimemail#31]
Go to https://backdrop.ddev.site/user/1/edit and try to save the option. It always returns empty on save.

**Comment by herbdool** [comment]
@alanmels if you create a PR, the @backdrop-contrib/bug-squad can merge it (after testing). The maintainer does not seem to be available at the moment.

**Comment by argiepiano** [comment]
PR #38

**Comment by herbdool** [comment]
Thank you @argiepiano! Merged this on behalf of Bug Squad.
