### ISSUE TITLE
Deprecated: required parameters following option parameters in PHP8.0+

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/mimemail#32]
PHP 8.0 doesn't like this.

> Deprecated: Required parameter $subject follows optional parameter $cc in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 247 
> Deprecated: Required parameter $body follows optional parameter $cc in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 247 
> Deprecated: Required parameter $langcode follows optional parameter $cc in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 247 
> Deprecated: Required parameter $settings follows optional parameter $cc in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 247 
> Deprecated: Required parameter $state follows optional parameter $cc in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 247 
> Deprecated: Required parameter $element follows optional parameter $cc in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 247 
> Deprecated: Required parameter $subject follows optional parameter $from_name in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 288 
> Deprecated: Required parameter $body follows optional parameter $from_name in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 288 
> Deprecated: Required parameter $settings follows optional parameter $from_name in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 288 
> Deprecated: Required parameter $state follows optional parameter $from_name in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 288 
> Deprecated: Required parameter $element follows optional parameter $from_name in /app/httpdocs/modules/contrib/mimemail/mimemail.rules.inc on line 288

Can probably fix this by either assigning defaults to each parameter even if hook_rules_action_info() requires it or changing the order of the parameters in both. The former would be easier.

**Comment by argiepiano** [comment]
The [solution adopted in the D7 version](https://git.drupalcode.org/project/mimemail/-/blob/7.x-1.x/mimemail.rules.inc#L275) is to not provide default values for any parameter. Rules will always provide a default value if the user doesn't specify a value for optional parameters in the Rules form.

**Comment by argiepiano** [comment]
PR #37

**Comment by herbdool** [comment]
Thank you @argiepiano. Merged this on behalf of Bug Squad.
