### ISSUE TITLE
Configurations are lost because of newly merged `mimemail_update_1000()`

### ISSUE THREAD

**Issue by argiepiano** [backdrop-contrib/mimemail#35]
PR #28 renamed the wrongly named `migrate_update_1000()` to `mimemail_update_1000()`.  This fix has not yet been included in a new release. 

Once you make a release of this, this will work fine if you are installing the module for the first time. BUT this will create a problem if you are updating the module. Basically, this update will run, and as a result, it will wipe out all the existing configurations. 

To reproduce this problem: 
1. Install the current released version. 
2. Inspect the config file, take note of the configurations there, such as `"mimemail_engine": "mimemail"`
3. Then manually add the `mimemail_update_1000()`  to `mimemail.install` and remove `migrate_update_1000()`. Backdrop will tell you that there are database updates that need to be run. 
4. Run the database update
5. Go back and check the configurations. They are all null

A solution for this is to first check if `mimemail.settings.json` already exists. If it does, this means that this is not a D7 upgrade, and it is not a new install of the module. Then we should skip overwriting the file.

**Comment by argiepiano** [comment]
PR #36

**Comment by herbdool** [comment]
Good point - best to be careful here. Merged this on behalf of Bug Squad.
